env:
  global:
    - secure: JLDrzbIXjH8SWABO96UdTUt+io4XJ98bwTAWA81m5Hl5mQZMu5i98LRwkXnn0vpGwB+kHBjjb44ROJ54nj8bkIwqyVHsJXpxA9BAo/E8cRpJSkWp/ufSkJ8XZT3zjbV8iYKSG1d1GsjES/7Q9UCdW1CcAMG2/vDFm9yLGng7fR8bL06Qn7Zly5LBA/Pxl5fCmwegMSpQK+5iaU2klIEvGUcj6vnCsBfOrHDkPPU3LDP0eN41p7YPQSuuVpiV1EBQDSxh3dGUskVCobzP1zyUbAuwn5kqIk6nqBvgX0lWmrE3a3591oTvP9UJCEnuIny6BnWlqlTVCuTsXvyK4zU31FWBtz+AL7yxROOOTfkxZjMHSv/TntYCyXLyObgnuN30cH9OhQWs0B4/my0L9FaiKLJKN3pTRghZOcmPdHUQERnMr+Zu0HR7qDajoamm8ne9dTp5SbPDQOIefmd/JMieZeBUt24qUlBeTzLvghDGbTVSZgMjWSYdSMPwws/CFjgm9ZZaIsBtjLTxRUE6c0YY1b+Kb1sAuVPFk54cUoWB3WzN6t5WsAqBl+biJXC9VDCp2o5KL58DphaOx/d3yhqkuWMHq2wWASckkg7rGVXg4fDOaWiMDpg9OCVpmDxqYQxZZzH25DZOFmdzj8NWFSMdnxNcK+aDclZWZZQ9npsQlWM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Suspicious.Snooping.Sniffing.Hacking.IP.Addresses
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
