env:
  global:
    - secure: dWx0x45xT5eHmPs9o4RLiDuxBYOyxUqqqjjLg9vYMY3q3gfIJInVEO5j1ax4ETT1G7lGs3TKgoo1PmfHNbrSeheIwJrSDH/qGK9JfQG0IoIjQjPavqH0a/iYeWY6fQ0K3szhbl3e+1IPCZrotA2NglUPSSbI7Kt2JsgB9fYelDQednbbhYtqtzB5hg0G444po0gHn1cmxpjk6om++gdJScR2Kw1Cz1lldjAMBUH74grLQcfAvP4vlsmAOSDwdvoFP8LHTRgXZ7CL2IwyHfJEmXmetP5hWPmRwYsKmAwNRovBRifnL9T5hny6y5wbnmR2PyL0bpMS/thviVM1KnTPpFnvTxd9mN5+1/JWDPjsG7PlZRpR12Q/hFYpaaffzsl9aUZkBDMzjAQzF5cWZ60ilGeMEE1zWTnCXLHRjZufFmsA2Iwc+BXAr7wO6j4QUEk2DakpZb8vducdOcDox2DqxCwgzsaCxJnuSZPKqXAPlIHD9wv9rEvFsXDy6rQn2OxddTqfpNf/wcRdHUUU/yUOB3tjz3+s6nZOTe0o4DwTRFGuMw4VgOhwRQwBJeNAiRSZJeU9wJhSGjt7/nPVDI6+Zs9ECVahsviwhHlq4UMo3pNuKfWuJ8JL84Rjh8UA8XNbH54mXmhPI5wE2Bo03MweLzpGOC9d0V9rIumNyVFfux4=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Suspicious.Snooping.Sniffing.Hacking.IP.Addresses
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
