env:
  global:
    - secure: jxZb2AaNg2j7IdjIzBHcSiEOLjLFy1/IJKTtcAya4zhMIq6kkEyF7q6uymF6WXXrHHnTHtV5fVZtsTgoyHL9pbf2u/astmmcNcZzqJYEMrDm/NLK0I2os7+VFoXeHaXtSCoWhZ9O8bKbj3cuOuKKWOU7umTRa26kBks3aEZ6ndRU4AOiWxxSdyg9XHje/VJlmd7xJYyVvpjTeVUanQtHwaRiYHa6t9390YEOgtoH0M7sQs/L9codOno2f/pwWKLC3XF0plIrcKZ7JZpxZGIHlXZlZRk1OFKFfDsLq8jwOc+QEQqaGKduRYA2Y54BtICLdWEgFnEWnbVgz62q/0GbzTantSct6GIkmnWc4DNyIzb9Zwu/IxZJT7uXq+pslIGa7z93/qu8JUQFTTxucFVi+Zcm75mNtNS9V5FB1Ds0yIQO9Bwwwae+Fw2uiHEQY//3OgLUoMwfXr+FnjcyPDuclFRgYcr56uxO/UvQ4prlNXSeGVpvFzvEClO3WgDF775CdtCSz0b8lGerABbau2s8ZEXvegN9V7HTb2jT9pGHAZIvRnU4fKkWIB9IcrYWjnRF5bWMJxxwmUS+6c3wE9+RwxPtma77o/OOrBCMhaiN6li1l5LQHlqEjO8maTNmV9FoBo52k8WgF+b5ZSU6AiEw/cNI3GCKQer/LybAYq53dNQ=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Suspicious.Snooping.Sniffing.Hacking.IP.Addresses
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
