env:
  global:
    - secure: Bre52wmmS/4t1LbYrv+bjMzYQG6whW3YtF2/9s/e7RgIOsPAbm1BItqgVxAcZefX0wmhQGcq4DUAO56b2Tw7JSyyX4rYVE4YIxBVaMJH90Dpi/NSK2WLEqqAGbjbMAaxtsb0CBm1LmJpyANwrg7SjQBdF95GSEkBNvnmGZdUBSLfa51nUgPYGE9QM+62SxzTh0bEqX52xnZGqYeAitVoBcB7WcPbe1t+SY9PxkooxMHUeD+HonyTIo8WOhjWu9ARamqotyBlPXysd1HRPVUUKD1oAsYal03fVqJoBdGC5DS5kCyeI7plHw/+273kzqILfS6tf1geHTgcS72dDOBXMk34OwH7BeMpSLeBQX3bxYZFC0hVqtid8cHObTtNZDGEcLVLx5Zi6ty8GyXwtKgw+Lx+muVU0+CrKCuUFOwSg2LUgM2GadgYyOMP0AwHDGgdEzC3B/AdMNiqClWl+Jdq9WzWD5GSix0PJbXhjsmj9kS1S3uO/Bf6C6JCCsCR/vEPHZbG5TcaPn20S1+zccZDSNqitG4D0tFhIQCm5sEs6p9QGxr4nKqvQHvVrjDc3syt7UjOT9lP7rMb8MYThEmgEo5+yJ0Qb/kFqX0ptsMh+pG6mQ+1ro6bRaW14uEA668JO71IsOBX+JrQNeX4lR62mQvLv38Ywu+Evd8RK4+NuoY=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Suspicious.Snooping.Sniffing.Hacking.IP.Addresses
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
