env:
  global:
    - secure: DBUw+CnA5OsWsl5siEkijbL4+OxelpL16Nm26JT6YjanNe6Gk2zDdld4JJdJQ9kVf6HpMdP6EWDkq5VZDFy6XNcI6q4Z1eJXZBI1R3IHLE+2PhVXAh79o/WHjGVd8yHgRUdcidM5QPt1bEdZK1cYhIXgKHQ0eBod+FsVKPhjDxJRmQ053c3waGEE4Jn7L/IRXhyk6APNCyfw2o6CT9yB5Ly/yzgHclpSWi0cztVZ2Ki1T3FwN2s/ixrlRHL/oW7M3iiF4qXg2CERIljwDem9x4asFAlicEJY/uWwvMa4nGibn2RFYoO02WkU6TlGSx5fnqymEVrSc+mdf1IwUeyBJBMq+A0jwLVwc0Upc28+uWv0H886f6DrDbaV6wPiTfD1udZjcKdyyZ7mCjCIWUFCmp94fbfrSeqgsR9mLe4ok7Qkz4KKHI/SsPbse43CxeXPuguBQ9PkdKVr1+bBt/950FrIBRFZYiaUR+LQpG9oYBge2YgbHqgIsYVLPabCKuaxqNhzb0LzXGqbZuB3wDeGlaIR0a/99hePxTSCApa6w6dH+PIcP+jkUwMXBLWCFFDMdS/fWdilDJeFi/pDW5GOgT3lskGyij+n3y4Ob9uMkyvXARMU7qyB3KR9UDKUEvUGCQr7rzGsMFHyFZ3Iv4e+ay6nRfog84CLKh7hRYvZ9dA=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Suspicious.Snooping.Sniffing.Hacking.IP.Addresses
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
